Hw02 unpack string
nicholas-sokolov/otus-golang pull request #2
Opened 2020-12-22 12:47 UTC by nicholas-sokolov

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-12-23 17:46 UTC, balabanovds requested changes
Хорошая работа.

Есть замечание по производительности и вопрос по тестам.

https://otus.ru/teacher-lk/homework/8009/9016/

2020-12-23 17:46 UTC, balabanovds commented on hw02_unpack_string/unpack.go
> +			result += strings.Repeat(string(alpha), int(digit)-'0')
дорогая операция `+=`, лучше использовать strings.Builder

2020-12-23 17:46 UTC, balabanovds commented on hw02_unpack_string/unpack_test.go
> +			println(r)
зачем это здесь?

2020-12-27 10:11 UTC, nicholas-sokolov commented on hw02_unpack_string/unpack_test.go
> +			println(r)
Это был мой дебаг, забыл удалить. Исправлено

2020-12-27 10:11 UTC, nicholas-sokolov commented on hw02_unpack_string/unpack.go
> +			result += strings.Repeat(string(alpha), int(digit)-'0')
Исправлено на использование strings.Builder

2020-12-27 12:49 UTC, balabanovds approved these changes
Работа принята. 10/10

Отмечу, что иногда в тестах удобно выводить данные через t.Log()
Он выводит только если стоит флаг v `go test -v ./...`

2020-12-27 14:15 UTC, merged